name: vitalyzer
description: "Vitalyzer Cross-Mobile App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flex_color_scheme: ^8.0.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/illustrations/analytics.png"
    - "assets/illustrations/camera.png"
    - "assets/illustrations/checklist.png"
    - "assets/illustrations/water-bottle.png"
