name: vitalyzer
description: "Vitalyzer Cross-Mobile App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flex_color_scheme: ^8.0.0
  google_fonts: ^6.2.1
  get: ^4.6.6
  shared_preferences: ^2.3.3
  camera: ^0.11.0+2
  image: ^4.3.0
  permission_handler: ^11.3.1
  image_picker: ^1.1.2
  syncfusion_flutter_gauges: ^28.1.33
  fl_chart: ^0.69.2
  flutter_svg: ^2.0.16
  sqflite: ^2.4.1
  path: ^1.9.0
  csv: ^6.0.0
  flutter_dotenv: ^5.2.1
  google_generative_ai: ^0.4.6
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  firebase_storage: ^12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/illustrations/analytics.png"
    - "assets/illustrations/camera.png"
    - "assets/illustrations/checklist.png"
    - "assets/illustrations/water-bottle.png"
    - "assets/icons/cooking-oil.svg"
    - "assets/icons/steak.svg"
    - "assets/icons/wheat.svg"
    - "assets/datasets/food_dataset.csv"
    - .env
